[tool]
[tool.poetry]
name = "gluejobutils"
version = "3.1.1"
description = "Python 2.7 utils for glue jobs"
license = "MIT"
authors = ["Robin Linacre <robinlinacre@hotmail.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "~2.7 || ^3.5"
